# Generated by Django 4.2.11 on 2024-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='requests',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
