# Generated by Django 4.2.11 on 2024-03-11 23:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='invitee',
        ),
        migrations.AddField(
            model_name='calendar',
            name='availability',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='availability',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitee_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='calendars.calendar'),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
