# Generated by Django 4.2.11 on 2024-03-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_remove_calendar_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='participants',
            field=models.TextField(default='[]'),
        ),
    ]
