# Generated by Django 4.2.11 on 2024-03-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_calendar_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calendar',
            name='finalized_schedule',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
